# Generated by Django 3.0.6 on 2020-06-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
